[platformio]
default_envs = esp32-s3-devkitc-1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
lib_deps =
    lvgl/lvgl@8.3.6
build_flags = 
    -O3 
    -funroll-loops 
    -DCORE_DEBUG_LEVEL=0
    -DLV_CONF_INCLUDE_SIMPLE
    -Ilib/hansolov2

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags = 
    ${env.build_flags} 
    -DARDUINO_USB_CDC_ON_BOOT=1 
    -DARDUINO_USB_MODE=1

[env:esp32-wroom]
board = esp32dev
